name: Semantic release

on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Setup python v11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest

      - name: Linting
        run: poetry run flake8 --exclude .git,__pycache__,build,dist,.venv

  release:
    needs: quality
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      - name: Fetch repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
