name: Create PR, code quality checks
on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Setup python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest

      - name: Linting
        run: poetry run flake8

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto Pull Request
          title: Auto pull request
          branch: ${{ github.ref }}
          base: main
